##Train Dataset

In [ ]:
# Dataset traning foundation:

#Dataset --> Neural Network(NN)
#                 |
#                 |
#                 v
#            Traning Pipeline


#1. We will build a simple neural network
#2. Train it on the real world dataset
#3. Will mimic the Pytorch workflow
#4. Will have a lot manual elements
#5. End result is not important

In [ ]:
#1. Load the dataset
#2. basic prepocessing
#3. Traning Process
  #a. Create the model
  #b. Forward pass
  #c. loss Calculation
  #d. Backprop
  #e. parameter update
#4. Model Evaluation

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [7]:
df.shape

(569, 33)

In [9]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [10]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

##Train test split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df['diagnosis'], test_size=0.2, random_state=42) # Assuming 'diagnosis' is the target column

#Scaling

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [24]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

#Label Encoding

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

Numpy Array to PyTorch Tensors

In [27]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

##Define Model

In [34]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.rand(1, dtype = torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    #calculate loss
    loss = - (y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

Important parameter

In [35]:
learning_rate = 0.1
epochs = 25

#Traing pipeline

In [36]:
#create model
model = MySimpleNN(X_train_tensor)

#define loop
for epochs in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)

  #loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epochs + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7461774286340175
Epoch: 2, Loss: 3.6264882408581256
Epoch: 3, Loss: 3.5048080042045813
Epoch: 4, Loss: 3.3784060554892035
Epoch: 5, Loss: 3.246734249421557
Epoch: 6, Loss: 3.1128332896633215
Epoch: 7, Loss: 2.975340873347191
Epoch: 8, Loss: 2.8337619882436034
Epoch: 9, Loss: 2.6838018354204083
Epoch: 10, Loss: 2.5311596614642418
Epoch: 11, Loss: 2.3755960410796613
Epoch: 12, Loss: 2.2215666939530574
Epoch: 13, Loss: 2.0675314784316585
Epoch: 14, Loss: 1.91302582062019
Epoch: 15, Loss: 1.764885516753299
Epoch: 16, Loss: 1.6249228585636277
Epoch: 17, Loss: 1.4906246815360358
Epoch: 18, Loss: 1.3675991993328653
Epoch: 19, Loss: 1.2573217584134158
Epoch: 20, Loss: 1.1630646067118486
Epoch: 21, Loss: 1.084927919686572
Epoch: 22, Loss: 1.0221083735990908
Epoch: 23, Loss: 0.9729387809958068
Epoch: 24, Loss: 0.9351508719027375
Epoch: 25, Loss: 0.906264857946447


In [37]:
model.bias

tensor([0.4173], dtype=torch.float64, requires_grad=True)

#Evaluation

In [48]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  #print(y_pred)
  y_pred = (y_pred > 0.5).float()
  #print(y_pred)
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')


Accuracy: 0.45690980553627014
